#ifndef YDWE_VERSION_H_INCLUDED
#define YDWE_VERSION_H_INCLUDED

#define YDWE_VERSION_MAJOR 2
#define YDWE_VERSION_MINOR 0
#define YDWE_VERSION_REVISED 1
#include <YDWEVersionBuild.h>

#endif // YDWE_VERSION_H_INCLUDED
