//===========================================================================
// 
// ∑ - Matrix 万能模板函数(修正版)v1.2
// 
//   Warcraft III map script
//   Generated by the Warcraft III World Editor
//   Date: Sat May 02 02:08:49 2026
//   Map Author: Warft_TigerCN
// 
//===========================================================================

//***************************************************************************
//*
//*  Global Variables
//*
//***************************************************************************

#define USE_BJ_ANTI_LEAK
#include <YDTrigger/Import.h>
#include <YDTrigger/YDTrigger.h>
globals
    // User-defined
    unit                    udg_u                      = null
    location                udg_p                      = null
    location                udg_l                      = null
    real                    udg_r                      = 0
    real                    udg_d                      = 0
    integer                 udg_I                      = 0
    string                  udg_s1
    string                  udg_s2

    // Generated
    sound                   gg_snd_RiflemanAttack1     = null
    sound                   gg_snd_RiflemanAttack2     = null
    sound                   gg_snd_MetalLightChopMetal1 = null
    sound                   gg_snd_MetalLightChopMetal2 = null
    sound                   gg_snd_MetalLightChopMetal3 = null
    trigger                 gg_trg_Init                = null
    trigger                 gg_trg_1_______u           = null
    trigger                 gg_trg_2__________u        = null
    trigger                 gg_trg_3_______u           = null
    trigger                 gg_trg_____________6       = null
    trigger                 gg_trg_______7             = null
    trigger                 gg_trg________________8    = null
    trigger                 gg_trg________________9    = null
#include <YDTrigger/Globals.h>
endglobals
#include <YDTrigger/Function.h>

function InitGlobals takes nothing returns nothing
    set udg_r = 0
    set udg_d = 0
    set udg_I = 0
    set udg_s1 = ""
    set udg_s2 = ""
endfunction

//***************************************************************************
//*
//*  Sounds
//*
//***************************************************************************

function InitSounds takes nothing returns nothing
    set gg_snd_RiflemanAttack1 = CreateSound( "Units\\Human\\Rifleman\\RiflemanAttack1.wav", false, true, true, 10, 10, "MissilesEAX" )
    call SetSoundParamsFromLabel( gg_snd_RiflemanAttack1, "RiflemanAttack1" )
    call SetSoundDuration( gg_snd_RiflemanAttack1, 702 )
    set gg_snd_RiflemanAttack2 = CreateSound( "Units\\Human\\Rifleman\\RiflemanAttack2.wav", false, true, true, 10, 10, "MissilesEAX" )
    call SetSoundParamsFromLabel( gg_snd_RiflemanAttack2, "RiflemanAttack1" )
    call SetSoundDuration( gg_snd_RiflemanAttack2, 702 )
    set gg_snd_MetalLightChopMetal1 = CreateSound( "Sound\\Units\\Combat\\MetalLightChopMetal1.wav", false, true, true, 10, 10, "CombatSoundsEAX" )
    call SetSoundParamsFromLabel( gg_snd_MetalLightChopMetal1, "MetalLightChopMetal" )
    call SetSoundDuration( gg_snd_MetalLightChopMetal1, 395 )
    set gg_snd_MetalLightChopMetal2 = CreateSound( "Sound\\Units\\Combat\\MetalLightChopMetal2.wav", false, true, true, 10, 10, "CombatSoundsEAX" )
    call SetSoundParamsFromLabel( gg_snd_MetalLightChopMetal2, "MetalLightChopMetal" )
    call SetSoundDuration( gg_snd_MetalLightChopMetal2, 402 )
    set gg_snd_MetalLightChopMetal3 = CreateSound( "Sound\\Units\\Combat\\MetalLightChopMetal3.wav", false, true, true, 10, 10, "CombatSoundsEAX" )
    call SetSoundParamsFromLabel( gg_snd_MetalLightChopMetal3, "MetalLightChopMetal" )
    call SetSoundDuration( gg_snd_MetalLightChopMetal3, 403 )
endfunction

//***************************************************************************
//*
//*  Unit Creation
//*
//***************************************************************************

//===========================================================================
function CreateUnitsForPlayer0 takes nothing returns nothing
    local player p = Player(0)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'Hvwd', -760.2, -378.5, 281.970 )
    call SetHeroLevel( u, 10, false )
    set u = CreateUnit( p, 'Obla', -890.7, -382.2, 288.640 )
    call SetHeroLevel( u, 10, false )
endfunction

//===========================================================================
function CreateNeutralHostile takes nothing returns nothing
    local player p = Player(PLAYER_NEUTRAL_AGGRESSIVE)
    local unit u
    local integer unitID
    local trigger t
    local real life

    set u = CreateUnit( p, 'hpea', 127.1, 287.7, 180.000 )
    set u = CreateUnit( p, 'hpea', 120.7, 410.5, 180.000 )
    set u = CreateUnit( p, 'hpea', 117.9, 531.6, 180.000 )
    set u = CreateUnit( p, 'hpea', 211.8, 290.0, 180.000 )
    set u = CreateUnit( p, 'hpea', 205.5, 412.7, 180.000 )
    set u = CreateUnit( p, 'hpea', 202.6, 533.8, 180.000 )
    set u = CreateUnit( p, 'hpea', 38.8, 286.6, 180.000 )
    set u = CreateUnit( p, 'hpea', 32.4, 409.4, 180.000 )
    set u = CreateUnit( p, 'hpea', 29.5, 530.5, 180.000 )
    set u = CreateUnit( p, 'hpea', 128.4, -1184.2, 180.000 )
    set u = CreateUnit( p, 'hpea', 122.0, -1061.4, 180.000 )
    set u = CreateUnit( p, 'hpea', 119.1, -940.3, 180.000 )
    set u = CreateUnit( p, 'hpea', 213.1, -1181.9, 180.000 )
    set u = CreateUnit( p, 'hpea', 206.7, -1059.1, 180.000 )
    set u = CreateUnit( p, 'hpea', 203.9, -938.0, 180.000 )
    set u = CreateUnit( p, 'hpea', 40.0, -1185.3, 180.000 )
    set u = CreateUnit( p, 'hpea', 33.6, -1062.5, 180.000 )
    set u = CreateUnit( p, 'hpea', 30.8, -941.4, 180.000 )
    set u = CreateUnit( p, 'hpea', 1097.9, -1160.7, 180.000 )
    set u = CreateUnit( p, 'hpea', 1091.5, -1037.9, 180.000 )
    set u = CreateUnit( p, 'hpea', 1088.6, -916.9, 180.000 )
    set u = CreateUnit( p, 'hpea', 1182.6, -1158.5, 180.000 )
    set u = CreateUnit( p, 'hpea', 1176.2, -1035.7, 180.000 )
    set u = CreateUnit( p, 'hpea', 1173.3, -914.6, 180.000 )
    set u = CreateUnit( p, 'hpea', 1009.5, -1161.8, 180.000 )
    set u = CreateUnit( p, 'hpea', 1003.1, -1039.1, 180.000 )
    set u = CreateUnit( p, 'hpea', 1000.2, -918.0, 180.000 )
    set u = CreateUnit( p, 'hpea', 1096.2, 342.7, 180.000 )
    set u = CreateUnit( p, 'hpea', 1089.8, 465.5, 180.000 )
    set u = CreateUnit( p, 'hpea', 1087.0, 586.6, 180.000 )
    set u = CreateUnit( p, 'hpea', 1180.9, 345.0, 180.000 )
    set u = CreateUnit( p, 'hpea', 1174.5, 467.8, 180.000 )
    set u = CreateUnit( p, 'hpea', 1171.7, 588.9, 180.000 )
    set u = CreateUnit( p, 'hpea', 1007.8, 341.6, 180.000 )
    set u = CreateUnit( p, 'hpea', 1001.4, 464.4, 180.000 )
    set u = CreateUnit( p, 'hpea', 998.6, 585.5, 180.000 )
endfunction

//===========================================================================
function CreatePlayerBuildings takes nothing returns nothing
endfunction

//===========================================================================
function CreatePlayerUnits takes nothing returns nothing
    call CreateUnitsForPlayer0(  )
endfunction

//===========================================================================
function CreateAllUnits takes nothing returns nothing
    call CreatePlayerBuildings(  )
    call CreateNeutralHostile(  )
    call CreatePlayerUnits(  )
endfunction

//***************************************************************************
//*
//*  Custom Script Code
//*
//***************************************************************************
//TESH.scrollpos=0
//TESH.alwaysfold=0

//***************************************************************************
//*
//*  Triggers
//*
//***************************************************************************

//===========================================================================
// Trigger: Init
//===========================================================================
function Trig_InitActions takes nothing returns nothing
    call FogModifierStart(CreateFogModifierRect(Player(0), FOG_OF_WAR_VISIBLE, bj_mapInitialPlayableArea, true, false))
    call DisplayTimedTextToPlayer(Player(0), 0, 0, 30, "TRIGSTR_082")
endfunction

//===========================================================================
function InitTrig_Init takes nothing returns nothing
    set gg_trg_Init = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_Init, "Init")
#endif
    call TriggerRegisterTimerEventSingle(gg_trg_Init, 0.00)
    call TriggerAddAction(gg_trg_Init, function Trig_InitActions)
endfunction

//===========================================================================
// Trigger: 1_冲锋
//
// (YDWEGetUnitID
//===========================================================================
function Trig_1_______uConditions takes nothing returns boolean
    return ((IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true) and (GetSpellAbilityId() == 'A000'))
endfunction

function Trig_1_______uActions takes nothing returns nothing
    call YDWESetAttackDamageWeaponType(ATTACK_TYPE_SIEGE, DAMAGE_TYPE_ENHANCED, WEAPON_TYPE_WHOKNOWS)
    call YDWETimerPatternRushSlide(GetTriggerUnit(), GetUnitFacing(GetTriggerUnit()), 800.00, 1, 0.03, 100.00, true, false, true, "origin", "Objects\\Spawnmodels\\Undead\\ImpaleTargetDust\\ImpaleTargetDust.mdl", "Abilities\\Spells\\Other\\CrushingWave\\CrushingWaveDamage.mdl")
endfunction

//===========================================================================
function InitTrig_1_______u takes nothing returns nothing
    set gg_trg_1_______u = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_1_______u, "1_冲锋")
#endif
    call TriggerRegisterAnyUnitEventBJ(gg_trg_1_______u, EVENT_PLAYER_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_1_______u, Condition(function Trig_1_______uConditions))
    call TriggerAddAction(gg_trg_1_______u, function Trig_1_______uActions)
endfunction

//===========================================================================
// Trigger: 2_月神箭
//
// (YDWEGetUnitID
//===========================================================================
function Trig_2__________uConditions takes nothing returns boolean
    return ((IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true) and (GetSpellAbilityId() == 'A001'))
endfunction

function Trig_2__________uActions takes nothing returns nothing
    call YDWESetAttackDamageWeaponType(ATTACK_TYPE_SIEGE, DAMAGE_TYPE_ENHANCED, WEAPON_TYPE_WHOKNOWS)
    call YDWESetLocalVariableLocation("l", GetUnitLoc(GetTriggerUnit()))
    call YDWESetLocalVariableLocation("p", GetSpellTargetLoc())
    call YDWESetLocalVariableReal("r", AngleBetweenPoints(YDWEGetLocalVariableLocation("l"), YDWEGetLocalVariableLocation("p")))
    call YDWESetLocalVariableUnit("u", CreateUnitAtLoc(GetOwningPlayer(GetTriggerUnit()), 'nalb', YDWEGetLocalVariableLocation("l"), YDWEGetLocalVariableReal("r")))
    call YDWESaveUnitByString(I2S(YDWEGetUnitID(YDWEGetLocalVariableUnit("u"))), "月神箭施放者", GetTriggerUnit())
    call YDWESaveUnitByInteger(YDWEGetUnitID(YDWEGetLocalVariableUnit("u")), 11, GetTriggerUnit())
    call YDWETimerPatternMoonPriestessArrow(YDWEGetLocalVariableUnit("u"), YDWEGetLocalVariableReal("r"), 1350.00, 2.00, 0.03, GetUnitAbilityLevelSwapped(GetSpellAbilityId(), GetTriggerUnit()), 'AHtb', 'npng', "thunderbolt", "overhead", "\"Objects\\\\Spawnmodels\\\\Undead\\\\ImpaleTargetDust\\\\ImpaleTargetDust.mdl\"")
    call RemoveLocation(YDWEGetLocalVariableLocation("l"))
    call RemoveLocation(YDWEGetLocalVariableLocation("p"))
    call YDWELocalVariableEnd()
endfunction

//===========================================================================
function InitTrig_2__________u takes nothing returns nothing
    set gg_trg_2__________u = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_2__________u, "2_月神箭")
#endif
    call TriggerRegisterAnyUnitEventBJ(gg_trg_2__________u, EVENT_PLAYER_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_2__________u, Condition(function Trig_2__________uConditions))
    call TriggerAddAction(gg_trg_2__________u, function Trig_2__________uActions)
endfunction

//===========================================================================
// Trigger: 3_跳劈
//
// (YDWEGetUnitID
//===========================================================================
function Trig_3_______uConditions takes nothing returns boolean
    return ((IsUnitType(GetTriggerUnit(), UNIT_TYPE_HERO) == true) and (GetSpellAbilityId() == 'A003'))
endfunction

function Trig_3_______uActions takes nothing returns nothing
    call YDWESetAttackDamageWeaponType(ATTACK_TYPE_SIEGE, DAMAGE_TYPE_ENHANCED, WEAPON_TYPE_WHOKNOWS)
    call YDWESetLocalVariableLocation("l", GetUnitLoc(GetTriggerUnit()))
    call YDWESetLocalVariableLocation("p", GetSpellTargetLoc())
    call YDWESetLocalVariableReal("r", AngleBetweenPoints(YDWEGetLocalVariableLocation("l"), YDWEGetLocalVariableLocation("p")))
    call YDWESetLocalVariableReal("d", DistanceBetweenPoints(YDWEGetLocalVariableLocation("l"), YDWEGetLocalVariableLocation("p")))
    call YDWETimerPatternJumpAttack(GetTriggerUnit(), YDWEGetLocalVariableReal("r"), YDWEGetLocalVariableReal("d"), 1, 0.03, 350.00, 1.00, "chest", "Abilities\\Spells\\Other\\CrushingWave\\CrushingWaveDamage.mdl")
    call RemoveLocation(YDWEGetLocalVariableLocation("l"))
    call RemoveLocation(YDWEGetLocalVariableLocation("p"))
    call YDWELocalVariableEnd()
endfunction

//===========================================================================
function InitTrig_3_______u takes nothing returns nothing
    set gg_trg_3_______u = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_3_______u, "3_跳劈")
#endif
    call TriggerRegisterAnyUnitEventBJ(gg_trg_3_______u, EVENT_PLAYER_UNIT_SPELL_EFFECT)
    call TriggerAddCondition(gg_trg_3_______u, Condition(function Trig_3_______uConditions))
    call TriggerAddAction(gg_trg_3_______u, function Trig_3_______uActions)
endfunction

//===========================================================================
// Trigger: 冲锋结束6
//===========================================================================
function Trig_____________6Actions takes nothing returns nothing
    call SelectUnitForPlayerSingle(GetLastAbilityCastingUnit(), GetOwningPlayer(GetLastAbilityCastingUnit()))
    call DisplayTextToPlayer(Player(0), 0, 0, (GetUnitName(GetLastAbilityCastingUnit()) + " 释放结束冲锋技能"))
    // 让单位施法结束后不会乱跑
    call IssueImmediateOrderById(GetLastAbilityCastingUnit(), 851972)
endfunction

//===========================================================================
function InitTrig_____________6 takes nothing returns nothing
    set gg_trg_____________6 = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_____________6, "冲锋结束6")
#endif
    call YDWESyStemAbilityCastingOverRegistTrigger(gg_trg_____________6, 6)
    call TriggerAddAction(gg_trg_____________6, function Trig_____________6Actions)
endfunction

//===========================================================================
// Trigger: 跳劈7
//===========================================================================
function Trig_______7Actions takes nothing returns nothing
    call DisplayTextToPlayer(Player(0), 0, 0, (GetUnitName(GetLastAbilityCastingUnit()) + " 释放结束跳劈技能"))
endfunction

//===========================================================================
function InitTrig_______7 takes nothing returns nothing
    set gg_trg_______7 = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg_______7, "跳劈7")
#endif
    call YDWESyStemAbilityCastingOverRegistTrigger(gg_trg_______7, 7)
    call TriggerAddAction(gg_trg_______7, function Trig_______7Actions)
endfunction

//===========================================================================
// Trigger: 月神箭结束8
//===========================================================================
function Trig________________8Actions takes nothing returns nothing
    // 注意，这里最后施放特殊技能的单位，是辅助单位；所以要用特别的方法获取技能施放单位
    call YDWESetLocalVariableUnit("u", YDWEGetUnitByInteger(YDWEGetUnitID(GetLastAbilityCastingUnit()), 11))
    call DisplayTextToPlayer(Player(0), 0, 0, (GetUnitName(GetLastAbilityTargetUnit()) + (" 不小心被 " + (GetUnitName(YDWEGetLocalVariableUnit("u")) + " 的月神箭颜射了！"))))
endfunction

//===========================================================================
function InitTrig________________8 takes nothing returns nothing
    set gg_trg________________8 = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg________________8, "月神箭结束8")
#endif
    call YDWESyStemAbilityCastingOverRegistTrigger(gg_trg________________8, 8)
    call TriggerAddAction(gg_trg________________8, function Trig________________8Actions)
endfunction

//===========================================================================
// Trigger: 月神箭结束9
//===========================================================================
function Trig________________9Actions takes nothing returns nothing
    // 注意，这里最后施放特殊技能的单位，是辅助单位；所以要用特别的方法获取技能施放单位
    call YDWESetLocalVariableUnit("u", YDWEGetUnitByInteger(YDWEGetUnitID(GetLastAbilityCastingUnit()), 11))
    call DisplayTextToPlayer(Player(0), 0, 0, (GetUnitName(YDWEGetLocalVariableUnit("u")) + " 的月神箭放了空枪，一无所获，比国足还不如，属于叉腰肌不够！"))
endfunction

//===========================================================================
function InitTrig________________9 takes nothing returns nothing
    set gg_trg________________9 = CreateTrigger()
#ifdef DEBUG
    call YDWESaveTriggerName(gg_trg________________9, "月神箭结束9")
#endif
    call YDWESyStemAbilityCastingOverRegistTrigger(gg_trg________________9, 9)
    call TriggerAddAction(gg_trg________________9, function Trig________________9Actions)
endfunction

//===========================================================================
function InitCustomTriggers takes nothing returns nothing
    call InitTrig_Init(  )
    call InitTrig_1_______u(  )
    call InitTrig_2__________u(  )
    call InitTrig_3_______u(  )
    call InitTrig_____________6(  )
    call InitTrig_______7(  )
    call InitTrig________________8(  )
    call InitTrig________________9(  )
endfunction

//***************************************************************************
//*
//*  Players
//*
//***************************************************************************

function InitCustomPlayerSlots takes nothing returns nothing

    // Player 0
    call SetPlayerStartLocation( Player(0), 0 )
    call SetPlayerColor( Player(0), ConvertPlayerColor(0) )
    call SetPlayerRacePreference( Player(0), RACE_PREF_HUMAN )
    call SetPlayerRaceSelectable( Player(0), true )
    call SetPlayerController( Player(0), MAP_CONTROL_USER )

endfunction

function InitCustomTeams takes nothing returns nothing
    // Force: TRIGSTR_002
    call SetPlayerTeam( Player(0), 0 )

endfunction

//***************************************************************************
//*
//*  Main Initialization
//*
//***************************************************************************

//===========================================================================
function main takes nothing returns nothing
    call SetCameraBounds( -1280.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 1280.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -1280.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 1024.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 1280.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -1536.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM) )
    call SetDayNightModels( "Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl" )
    call NewSoundEnvironment( "Default" )
    call SetAmbientDaySound( "LordaeronSummerDay" )
    call SetAmbientNightSound( "LordaeronSummerNight" )
    call SetMapMusic( "Music", true, 0 )
    call InitSounds(  )
    call CreateAllUnits(  )
    call InitBlizzard(  )
    call InitGlobals(  )
    call InitCustomTriggers(  )

endfunction

//***************************************************************************
//*
//*  Map Configuration
//*
//***************************************************************************

function config takes nothing returns nothing
    call SetMapName( "TRIGSTR_003" )
    call SetMapDescription( "" )
    call SetPlayers( 1 )
    call SetTeams( 1 )
    call SetGamePlacement( MAP_PLACEMENT_USE_MAP_SETTINGS )

    call DefineStartLocation( 0, -64.0, -320.0 )

    // Player setup
    call InitCustomPlayerSlots(  )
    call SetPlayerSlotAvailable( Player(0), MAP_CONTROL_USER )
    call InitGenericPlayerSlots(  )
endfunction

#ifndef YDWETimerPatternIncluded
#define YDWETimerPatternIncluded

#include "YDWEBase.j"

library_once YDWETimerPattern initializer Init requires YDWEBase

//***************************************************
//* �� - Matrix ����ģ�庯��
//*--------------------
//* ���ߣ�Warft_TigerCN  �����Ż���Fetrix_sai
//***************************************************

    #define TIMER_PATTERN_RADIUS 120.0

    private keyword Thread

    globals
        private boolexpr Bexpr = null
        private rect Area = null
        private Thread tmp_data
        private location yd_loc = Location(0.0, 0.0)
    endglobals

    private struct YDVector3
        real x
        real y
        real z
    endstruct

    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    //                                       Timer Pattern Union                                              //
    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    private function SingleMagic takes unit sour, unit targ, real x, real y, real h, integer uid, integer aid, integer lv, integer order returns nothing
        local unit dummy = CreateUnit(GetOwningPlayer(sour), uid, x, y, GetUnitFacing(sour))
        call UnitApplyTimedLife(dummy, 'BHwe', 1.0)
        call UnitAddAbility(dummy, aid)
        call SetUnitAbilityLevel(dummy, aid, lv)
        call SetUnitFlyHeight(dummy, h, 0.0)
        call IssueTargetOrderById(dummy, order, targ)
        //debug call BJDebugMsg("Target order")
        set dummy = null
    endfunction

    private function GetUnitZ takes unit u returns real
        call MoveLocation(yd_loc, GetUnitX(u), GetUnitY(u))
        return GetUnitFlyHeight(u) + GetLocationZ(yd_loc)
    endfunction

    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    //                                            Filter Funcs                                                //
    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    private function EnemyFilter takes unit u, unit caster returns boolean
        return IsUnitType(u, UNIT_TYPE_MAGIC_IMMUNE) == false and IsUnitType(u, UNIT_TYPE_RESISTANT) == false /*
        */ and IsUnitType(u, UNIT_TYPE_SLEEPING) == false     and GetUnitState(u, UNIT_STATE_LIFE) > 0.405    /*
        */ and IsUnitType(u, UNIT_TYPE_STRUCTURE) == false    and IsUnitIllusion(u) == false                  /*
        */ and IsUnitHidden(u) == false                       and IsUnitEnemy(u, GetOwningPlayer(caster))     /*
        */ and IsUnitVisible(u, GetOwningPlayer(caster))
    endfunction

    private function TreeFilter takes nothing returns boolean
        local integer id = GetDestructableTypeId(GetFilterDestructable())
        return id == 'LTlt' or id == 'ATtr' or id == 'BTtw' or id == 'KTtw' /*
          */or id == 'YTft' or id == 'JTct' or id == 'YTst' or id == 'YTct' /*
          */or id == 'YTwt' or id == 'JTtw' or id == 'DTsh' or id == 'FTtw' /*
          */or id == 'CTtr' or id == 'ITtw' or id == 'NTtw' or id == 'OTtw' /*
          */or id == 'ZTtw' or id == 'WTst' or id == 'GTsh' or id == 'VTlt' /*
          */or id == 'WTtw' or id == 'ATtc' or id == 'BTtc' or id == 'CTtc' /*
          */or id == 'ITtc' or id == 'NTtc' or id == 'ZTtc'
    endfunction

    private function DamageFilter takes nothing returns boolean
        local unit   u = GetFilterUnit()
        local Thread d = tmp_data
        if not(IsUnitInGroup(u, d.g)) and d.switch != 0 and EnemyFilter(u, d.caster) then
            call UnitDamageTarget(d.caster, u, d.amount, true, true, bj_lastSetAttackType, bj_lastSetDamageType, bj_lastSetWeaponType)
            call DestroyEffect(AddSpecialEffectTarget(d.dsfx, u, d.part))
            if d.skills > '0000' and d.skills != null and d.order > 0 and d.order != null then
                call SingleMagic(d.caster, u, d.pos.x, d.pos.y, GetUnitFlyHeight(d.obj), d.unitid, d.skills, d.level, d.order)
            endif
            if not(d.recycle) then
                //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r A one-time.")
                set d.switch = 0
            endif
            set d.target = u
            //call GroupAddUnit(d.g, u)
            set u = null
            return true
        endif
        set u = null
        return false
    endfunction

    private function TreeKill takes nothing returns nothing
        local destructable d = GetEnumDestructable()
        if GetWidgetLife(d) > 0.405 then
            call KillDestructable(d)
        endif
        set d = null
    endfunction

    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    //                                         Major Structure Code                                           //
    //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    private struct Thread
        YDVector3 des //destination
        YDVector3 pos //position
        YDVector3 vel //velocity
        unit caster
        unit source
        unit target
        unit obj
        real ac
        real bc
        real dist
        real step
        real amount
        integer switch
        integer follow
        integer unitid
        integer skills
        integer order
        integer level
        string dsfx
        string gsfx
        string wsfx
        string part
        boolean recycle
        boolean killdest
        boolean volume
        group g
        timer t

        static method operator [] takes handle h returns thistype
            return YDWEGetIntegerByString("YDWETimerPattern.", I2S(YDWEH2I(h)))
        endmethod

        static method operator []= takes handle h, thistype value returns nothing
            call YDWESaveIntegerByString("YDWETimerPattern.", I2S(YDWEH2I(h)), value)
        endmethod

        static method flush takes handle h returns nothing
            call YDWEFlushStoredIntegerByString("YDWETimerPattern.", I2S(YDWEH2I(h)))
        endmethod

        method operator x= takes real value returns nothing
            set .pos.x = value
            call SetUnitX(.obj, value)
        endmethod

        method operator y= takes real value returns nothing
            set .pos.y = value
            call SetUnitY(.obj, value)
        endmethod

        method operator z= takes real value returns nothing
            set .pos.z = value
            call MoveLocation(yd_loc, .pos.x, .pos.y)
            call SetUnitFlyHeight(.obj, value - GetLocationZ(yd_loc), 0)
        endmethod

        method onDestroy takes nothing returns nothing
            //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r Knockback stopped!")
            call Thread.flush(.obj)
            call Thread.flush(.t)
            call GroupClear(.g)
            call DestroyGroup(.g)
            call PauseTimer(.t)
            call DestroyTimer(.t)
            call .des.destroy()
            call .pos.destroy()
            call .vel.destroy()
            set .caster = null
            set .target = null
            set .obj = null
            set .g = null
            set .t = null
            set .amount = 0
            set .skills = 0
            set .order = 0
            set .dsfx = ""
            set .gsfx = ""
            set .wsfx = ""
            set .part = ""
        endmethod
    endstruct

    private struct Parabola extends Thread

        static method move takes nothing returns nothing
            local thistype this = Thread[GetExpiredTimer()]
            //local real vx = .des.x - .pos.x
            //local real vy = .des.y - .pos.y
            //local real vz = .des.z - .pos.z
            //if vx * vx + vy * vy + vz * vz > 900.0 then
                set .x = GetUnitX(.obj) + .vel.x //.pos.x + .vel.x
                set .y = GetUnitY(.obj) + .vel.y //.pos.y + .vel.y
                set .z = GetUnitZ(.obj) + .ac * .step * 2 + .ac * .dist + .bc //.pos.z + .ac * .step * 2 + .ac * .dist + .bc
                set .step = .step + .dist
                //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r high = ." + R2S(GetLocationZ(yd_loc)))
                if YDWECoordinateX(.pos.x) != .pos.x or YDWECoordinateY(.pos.y) != .pos.y or .pos.z <= GetLocationZ(yd_loc) then
                    set .switch = 0
                endif
                if .amount > 0.0 then
                    //call this.damage(.caster, .pos.x + .vel.x, .pos.y + .vel.y, GetUnitZ(.obj), false, false)
                    set tmp_data = integer(this)
                    call GroupEnumUnitsInRange(.g, .pos.x + .vel.x, .pos.y + .vel.y, TIMER_PATTERN_RADIUS, function DamageFilter)
                    //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r Area damage.")
                endif
            //else
                //set .switch = 0
            //endif

            if .switch == 0 then
                call SetUnitFlyHeight(.obj, GetUnitDefaultFlyHeight(.obj), 200.0)
                call SetUnitTimeScale(.obj, 1)
                //YDWETriggerEvent
                call YDWESyStemAbilityCastingOverTriggerAction(.obj, 7)
                call this.destroy()
            endif
        endmethod

        static method create takes unit source, unit object, real angle, real distance, real time, real interval, real high, real damage, string attach, string deff returns thistype
            local thistype this = thistype.allocate()
            local real vx = 0.0
            local real vy = 0.0
            local real vz = 0.0
            set .des = YDVector3.create()
            set .pos = YDVector3.create()
            set .vel = YDVector3.create()
            set .pos.x = GetUnitX(object)
            set .pos.y = GetUnitY(object)
            set .pos.z = GetUnitZ(object)
            set .des.x = .pos.x + distance * Cos(angle)
            set .des.y = .pos.y + distance * Sin(angle)
            call MoveLocation(yd_loc, .des.x, .des.y)
            set .des.z = GetLocationZ(yd_loc)
            if .pos.z > .des.z then
                set high = high + .pos.z
            else
                set high = high + .des.z
            endif
            set .ac = (2 * (.pos.z + .des.z) - 4 * high) / (distance * distance)
            set .bc = (.des.z - .pos.z - .ac * distance * distance) / distance
            set .dist = distance * interval / time
            set .ac = .ac * .dist
            set .bc = .bc * .dist
            set .vel.x = .dist * Cos(angle)
            set .vel.y = .dist * Sin(angle)
            set .step = 0.0
            set .caster = source
            set .obj = object
            set .amount = damage
            set .dsfx = deff
            set .part = attach
            set .switch = 1
            set .recycle = true
            set .t = CreateTimer()
            set .g = CreateGroup()
            call UnitAddAbility(.obj, 'Amrf')
            call UnitRemoveAbility(.obj, 'Amrf')
            call TimerStart(.t, interval, true, function thistype.move)
            call GroupAddUnit(.g, object)
            set Thread[object] = integer(this)
            set Thread[.t] = integer(this)
            return this
        endmethod

    endstruct

    // uniform speed
    private struct Linear extends Thread

        static method move takes nothing returns nothing
            local thistype this = Thread[GetExpiredTimer()]
            if .step > .dist then
                set .x = GetUnitX(.obj) + .vel.x //.pos.x + .vel.x
                set .y = GetUnitY(.obj) + .vel.y //.pos.y + .vel.y
                //set .pos.z = GetUnitZ(.obj)
                set .step = .step - .dist
                //call this.damage(.caster, .pos.x, .pos.y, .pos.z, true, true)
                set tmp_data = integer(this)
                call GroupEnumUnitsInRange(.g, .pos.x + .vel.x, .pos.y + .vel.y, TIMER_PATTERN_RADIUS, function DamageFilter)
                if YDWECoordinateX(.pos.x) != .pos.x or YDWECoordinateY(.pos.y) != .pos.y then
                    set .switch = 0
                endif
            else
                set .switch = 0
            endif

            if .switch == 0 then
                // YDWETriggerEvent
                if .target != null then
                    //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r  |cffff0000" + GetUnitName(.target) + "|r was hit!!!")
                    //call YDWESaveUnitByString(I2S(YDWEH2I(.caster)), "MoonPriestessArrow", .target)
                    set bj_lastAbilityTargetUnit = .target
                    call YDWESyStemAbilityCastingOverTriggerAction(.caster, 8)
                else
                    call YDWESyStemAbilityCastingOverTriggerAction(.caster, 9)
                endif
                //call KillUnit(.obj)
                call RemoveUnit(.obj)
                call this.destroy()
            endif
        endmethod

        static method create takes unit source, unit object, real angle, real distance, real time, real interval, integer uid, integer aid, integer lv, integer orderid, string attach, string sfx returns thistype
            local thistype this = thistype.allocate()
            set .des = YDVector3.create()
            set .pos = YDVector3.create()
            set .vel = YDVector3.create()
            set .step = distance
            set .dist = distance * interval / time
            set .vel.x = .dist * Cos(angle)
            set .vel.y = .dist * Sin(angle)
            set .pos.x = GetUnitX(object)
            set .pos.y = GetUnitY(object)
            set .caster = source
            set .obj = object
            set .unitid = uid
            set .skills = aid
            set .level = lv
            set .order = orderid
            set .part = attach
            set .gsfx = sfx
            set .switch = 1
            set .recycle = false
            set .t = CreateTimer()
            set .g = CreateGroup()
            call TimerStart(.t, interval, true, function thistype.move)
            set Thread[.t] = integer(this)
            return this
        endmethod

    endstruct

    // Uniform deceleration
    private struct Deceleration extends Thread

        static method move takes nothing returns nothing
            local thistype this = Thread[GetExpiredTimer()]
            local real xp = GetUnitX(.obj) + .dist * .vel.x
            local real yp = GetUnitY(.obj) + .dist * .vel.y
            if .volume == false then
                //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |rPathable without terrain.")
                if IsTerrainPathable(xp, yp, PATHING_TYPE_WALKABILITY) then
                    set .switch = 0
                else
                    set .x = xp
                    set .y = yp
                endif
            else
                set .x = xp
                set .y = yp
            endif
            if .follow == 0 then
                if GetUnitFlyHeight(.obj) < 5. then
                    if IsTerrainPathable(.pos.x, .pos.y, PATHING_TYPE_FLOATABILITY) then
                        call DestroyEffect(AddSpecialEffect(.gsfx, .pos.x, .pos.y))
                    else
                        call DestroyEffect(AddSpecialEffect(.wsfx, .pos.x, .pos.y))
                    endif
                endif
            endif
            set .follow = .follow + 1
            if .follow == 2 then
                set .follow = 0
            endif
            if .killdest then
                call MoveRectTo(Area, .pos.x, .pos.y)
                call EnumDestructablesInRect(Area, Bexpr, function TreeKill)
            endif
            if .amount > 0.0 then
                //call this.damage(.caster, .pos.x, .pos.y, 0.0, false, .recycle)
                set tmp_data = integer(this)
                call GroupEnumUnitsInRange(.g, .pos.x, .pos.y, TIMER_PATTERN_RADIUS, function DamageFilter)
            endif
            set .dist = .dist - .step
            if .dist <= 0.0 or YDWECoordinateX(.pos.x) != .pos.x or YDWECoordinateY(.pos.y) != .pos.y then
                set .switch = 0
            endif

            if .switch == 0 then
                call SetUnitFlyHeight(.obj, GetUnitDefaultFlyHeight(.obj), 200.0)
                call SetUnitTimeScale(.obj, 1)
                // YDWETriggerEvent
                call YDWESyStemAbilityCastingOverTriggerAction(.obj, 6)
                call this.destroy()
            endif
        endmethod

        static method create takes unit source, unit object, real angle, real distance, real time, real interval, real damage, boolean killtrees, boolean cycle, boolean path, string part, string geff, string weff returns thistype
            local thistype this = thistype.allocate() //thistype(Thread[object])
            local real vx = 0.0
            local real vy = 0.0
            local real l  = 0.0
            set .des = YDVector3.create()
            set .pos = YDVector3.create()
            set .vel = YDVector3.create()
            set .vel.x = Cos(angle)
            set .vel.y = Sin(angle)
            set .dist  = 2 * distance * interval / time
            set .step  = .dist * interval / time
            set .pos.x = GetUnitX(object)
            set .pos.y = GetUnitY(object)
            set .caster = source
            set .obj = object
            set .amount = damage
            set .killdest = killtrees
            set .recycle = cycle
            set .volume = path
            set .gsfx = geff
            set .wsfx = weff
            set .switch = 1
            set .follow = 0
            set .g = CreateGroup()
            set .t = CreateTimer()
            call TimerStart(.t, interval, true, function thistype.move)
            set Thread[.t] = integer(this)
            return this
        endmethod
    endstruct


    // Jump Attack PUI
    function YDWETimerPatternJumpAttack takes unit u, real face, real dis, real lasttime, real timeout, real high, real damage, string part, string dsfx returns nothing
        if u == null then
            //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r No object!")
            return
        endif
        call Parabola.create(u, u, Deg2Rad(face), RMaxBJ(dis, 0), RMaxBJ(lasttime, 0), RMaxBJ(timeout, 0), high, damage, part, dsfx)
    endfunction

    // Moon Priestess Arrow PUI
    function YDWETimerPatternMoonPriestessArrow takes unit u, real face, real dis, real lasttime, real timeout, integer lv, integer aid, integer uid, string order, string part, string dsfx returns nothing
        local unit sour = null
        if u == null then
            //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r No object!")
            return
        endif
        set sour = YDWEGetUnitByString(I2S(YDWEH2I(u)), "MoonPriestessArrow")
        if sour == null then
            set sour = u
        endif
        call Linear.create(sour, u, Deg2Rad(face), RMaxBJ(dis, 0), RMaxBJ(lasttime, 0), RMaxBJ(timeout, 0), uid, aid, IMaxBJ(lv, 1), OrderId(order), part, dsfx)
        //call YDWEFlushMissionByString(I2S(YDWEH2I(u)))
        set sour = null
    endfunction

    // Rush Slide PUI
    function YDWETimerPatternRushSlide takes unit u, real face, real dis, real lasttime, real timeout, real damage, boolean killtrees, boolean cycle, boolean path, string part, string gsfx, string wsfx returns nothing
        if u == null then
            //debug call BJDebugMsg("|cff00ff00[YDWE] Timer Pattern : |r No object!")
            return
        endif
        call Deceleration.create(u, u, Deg2Rad(face), RMaxBJ(dis, 0), RMaxBJ(lasttime, 0), RMaxBJ(timeout, 0), damage, killtrees, cycle, path, part, gsfx, wsfx)
    endfunction

    private function Init takes nothing returns nothing
        set Area  = Rect(-TIMER_PATTERN_RADIUS, -TIMER_PATTERN_RADIUS, TIMER_PATTERN_RADIUS, TIMER_PATTERN_RADIUS)
        set Bexpr = Filter(function TreeFilter)
    endfunction

	#undef TIMER_PATTERN_RADIUS
endlibrary

#endif /// YDWETimerPatternIncluded

#ifndef YDWEBaseIncluded
#define YDWEBaseIncluded

library YDWEBase initializer InitializeYD

#if WARCRAFT_VERSION >= 124
#  include "Base/YDWEBase_hashtable.j"
#else 
#  include "Base/YDWEBase_returnbug.j" 
#endif
#    
#  include "Base/YDWEBase_common.j"

endlibrary

#endif // YDWEBaseIncluded

#ifndef YDWELocalVariableIncluded
#define YDWELocalVariableIncluded

#include "YDWEBase.j"

library YDWELocalVariable requires YDWEBase

function YDWELocalVariableInitiliation takes nothing returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"GlobalsTriggerRunSteps")
    set TriggerRunSteps=TriggerRunSteps+1
    call YDWESaveIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"GlobalsTriggerRunSteps",TriggerRunSteps)
    call YDWESaveIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps",TriggerRunSteps)
endfunction

function YDWEWaitForLocalVariable takes real time returns nothing
    local integer TriggerRunSteps=YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
// call BJDebugMsg("等待之前TriggerRunSteps= "+I2S(TriggerRunSteps))
    call TriggerSleepAction(time)
// call BJDebugMsg("等待之后TriggerRunSteps= "+I2S(TriggerRunSteps))
    call YDWESaveIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps",TriggerRunSteps)
endfunction

function YDWELocalVariableEnd takes nothing returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWEFlushMissionByString(dir)
endfunction

//integer
function YDWESetLocalVariableInteger takes string s,integer i returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s,i)
endfunction

function YDWEGetLocalVariableInteger takes string s returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s)
endfunction

function YDWESetLocalVariableIntegerArray takes string s,integer index,integer i returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s+I2S(index),i)
endfunction

function YDWEGetLocalVariableIntegerArray takes string s,integer index returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s+I2S(index))
endfunction

//real
function YDWESetLocalVariableReal takes string s,real R returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveRealByString(dir,s,R)
endfunction

function YDWEGetLocalVariableReal takes string s returns real
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetRealByString(dir,s)
endfunction

function YDWESetLocalVariableRealArray takes string s,integer index,real R returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveRealByString(dir,s+I2S(index),R)
endfunction

function YDWEGetLocalVariableRealArray  takes string s,integer index returns real
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetRealByString(dir,s+I2S(index))
endfunction
//string
function YDWESetLocalVariableString takes string s,string str returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveStringByString(dir,s,str)
endfunction

function YDWEGetLocalVariableString takes string s returns string
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetStringByString(dir,s)
endfunction

function YDWESetLocalVariableStringArray takes string s,integer index,string str returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveStringByString(dir,s+I2S(index),str)
endfunction

function YDWEGetLocalVariableStringArray takes string s,integer index returns string
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetStringByString(dir,s+I2S(index))
endfunction
//boolean
function YDWESetLocalVariableBoolean takes string s,boolean bl returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveBooleanByString(dir,s,bl)
endfunction

function YDWEGetLocalVariableBoolean takes string s returns boolean
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetBooleanByString(dir,s)
endfunction

function YDWESetLocalVariableBooleanArray takes string s,integer index,boolean bl returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveBooleanByString(dir,s+I2S(index),bl)
endfunction

function YDWEGetLocalVariableBooleanArray takes string s,integer index returns boolean
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetBooleanByString(dir,s+I2S(index))
endfunction
//unit
function YDWESetLocalVariableUnit takes string s,unit u returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveUnitByString(dir,s,u)
endfunction

function YDWEGetLocalVariableUnit takes string s returns unit
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetUnitByString(dir,s)
endfunction

function YDWESetLocalVariableUnitArray takes string s,integer index,unit u returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveUnitByString(dir,s+I2S(index),u)
endfunction

function YDWEGetLocalVariableUnitArray takes string s,integer index returns unit
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetUnitByString(dir,s+I2S(index))
endfunction

//unit code
function YDWESetLocalVariableUnitID takes string s,integer uid returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s,uid)
endfunction

function YDWEGetLocalVariableUnitID takes string s returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s)
endfunction

function YDWESetLocalVariableUnitIDArray takes string s,integer index,integer uid returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s+I2S(index),uid)
endfunction

function YDWEGetLocalVariableUnitIDArray takes string s,integer index returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s+I2S(index))
endfunction
//ability code
function YDWESetLocalVariableAbilityID takes string s,integer abid returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s,abid)
endfunction

function YDWEGetLocalVariableAbilityID takes string s returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s)
endfunction

function YDWESetLocalVariableAbilityIDArray takes string s,integer index,integer abid returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s+I2S(index),abid)
endfunction

function YDWEGetLocalVariableAbilityIDArray takes string s,integer index returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s+I2S(index))
endfunction
//item
function YDWESetLocalVariableItem takes string s,item it returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveItemByString(dir,s,it)
endfunction

function YDWEGetLocalVariableItem takes string s returns item
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetItemByString(dir,s)
endfunction

function YDWESetLocalVariableItemArray takes string s,integer index,item it returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveItemByString(dir,s+I2S(index),it)
endfunction

function YDWEGetLocalVariableItemArray takes string s,integer index returns item
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetItemByString(dir,s+I2S(index))
endfunction
//item code
function YDWESetLocalVariableItemID takes string s,integer itid returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s,itid)
endfunction

function YDWEGetLocalVariableItemID takes string s returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s)
endfunction

function YDWESetLocalVariableItemIDArray takes string s,integer index,integer itid returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveIntegerByString(dir,s+I2S(index),itid)
endfunction

function YDWEGetLocalVariableItemIDArray takes string s,integer index returns integer
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetIntegerByString(dir,s+I2S(index))
endfunction
//location
function YDWESetLocalVariableLocation takes string s,location point returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveLocationByString(dir,s,point)
endfunction

function YDWEGetLocalVariableLocation takes string s returns location
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetLocationByString(dir,s)
endfunction

function YDWESetLocalVariableLocationArray takes string s,integer index,location point returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveLocationByString(dir,s+I2S(index),point)
endfunction

function YDWEGetLocalVariableLocationArray takes string s,integer index returns location
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetLocationByString(dir,s+I2S(index))
endfunction
//group
function YDWESetLocalVariableGroup takes string s,group g returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveGroupByString(dir,s,g)
endfunction

function YDWEGetLocalVariableGroup takes string s returns group
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetGroupByString(dir,s)
endfunction

function YDWESetLocalVariableGroupArray takes string s,integer index,group g returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveGroupByString(dir,s+I2S(index),g)
endfunction

function YDWEGetLocalVariableGroupArray takes string s,integer index returns group
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetGroupByString(dir,s+I2S(index))
endfunction
//effect
function YDWESetLocalVariableEffect takes string s,effect e returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveEffectByString(dir,s,e)
endfunction

function YDWEGetLocalVariableEffect takes string s returns effect
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetEffectByString(dir,s)
endfunction

function YDWESetLocalVariableEffectArray takes string s,integer index,effect e returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveEffectByString(dir,s+I2S(index),e)
endfunction

function YDWEGetLocalVariableEffectArray takes string s,integer index returns effect
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetEffectByString(dir,s+I2S(index))
endfunction

//rect
function YDWESetLocalVariableRect takes string s,rect rt returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveRectByString(dir,s,rt)
endfunction

function YDWEGetLocalVariableRect takes string s returns rect
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetRectByString(dir,s)
endfunction

function YDWESetLocalVariableRectArray takes string s,integer index,rect rt returns nothing
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    call YDWESaveRectByString(dir,s+I2S(index),rt)
endfunction

function YDWEGetLocalVariableRectArray takes string s,integer index returns rect
    local integer TriggerRunSteps = YDWEGetIntegerByString(I2S(YDWEH2I(GetTriggeringTrigger())),"TriggerRunSteps")
    local string dir = I2S(YDWEH2I(GetTriggeringTrigger()))+I2S(TriggerRunSteps)
    return YDWEGetRectByString(dir,s+I2S(index))
endfunction


endlibrary 

#endif /// YDWELocalVariableIncluded

/**/
